// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home documents */
type HomeDocumentData = Record<string, never>;
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;
export type AllDocumentTypes = HomeDocument;
/**
 * Primary content in Home → Primary
 *
 */
interface HomeSliceDefaultPrimary {
    /**
     * Title field in *Home → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Passport
     * - **API ID Path**: home.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Home → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: home.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Home Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Home`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HomeSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Home*
 *
 */
type HomeSliceVariation = HomeSliceDefault;
/**
 * Home Shared Slice
 *
 * - **API ID**: `home`
 * - **Description**: `Home`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeSlice = prismicT.SharedSlice<"home", HomeSliceVariation>;
/**
 * Primary content in WorkingProcess → Primary
 *
 */
interface WorkingProcessSliceDefaultPrimary {
    /**
     * ProcessTitle field in *WorkingProcess → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: working_process.primary.process_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    process_title: prismicT.TitleField;
    /**
     * ProcessText field in *WorkingProcess → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: working_process.primary.process_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    process_text: prismicT.RichTextField;
    /**
     * ProcessImage field in *WorkingProcess → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: working_process.primary.process_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    process_image: prismicT.ImageField<never>;
    /**
     * ProcessButton field in *WorkingProcess → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: working_process.primary.process_button
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    process_button: prismicT.RichTextField;
}
/**
 * Item in WorkingProcess → Items
 *
 */
export interface WorkingProcessSliceDefaultItem {
    /**
     * ProcessLabel field in *WorkingProcess → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: working_process.items[].process_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    process_label: prismicT.RichTextField;
    /**
     * ProcessDescription field in *WorkingProcess → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: working_process.items[].process_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    process_description: prismicT.RichTextField;
}
/**
 * Default variation for WorkingProcess Slice
 *
 * - **API ID**: `default`
 * - **Description**: `WorkingProcess`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorkingProcessSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<WorkingProcessSliceDefaultPrimary>, Simplify<WorkingProcessSliceDefaultItem>>;
/**
 * Slice variation for *WorkingProcess*
 *
 */
type WorkingProcessSliceVariation = WorkingProcessSliceDefault;
/**
 * WorkingProcess Shared Slice
 *
 * - **API ID**: `working_process`
 * - **Description**: `WorkingProcess`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorkingProcessSlice = prismicT.SharedSlice<"working_process", WorkingProcessSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomeDocumentData, HomeDocument, AllDocumentTypes, HomeSliceDefaultPrimary, HomeSliceDefault, HomeSliceVariation, HomeSlice, WorkingProcessSliceDefaultPrimary, WorkingProcessSliceDefaultItem, WorkingProcessSliceDefault, WorkingProcessSliceVariation, WorkingProcessSlice };
    }
}
