// Code generated by Slice Machine. DO NOT EDIT.

import advice_list from './advice_list';
import blockquote from './blockquote';
import content from './content';
import delivery_method from './delivery_method';
import faq from './faq';
import info from './info';
import payment_information from './payment_information';
import proceed_to_checkout from './proceed_to_checkout';
import requirements from './requirements';
import review_and_pay from './review_and_pay';
import reviews from './reviews';
import shipping_information from './shipping_information';
import step_toolbar from './step_toolbar';
import values from './values';
import why from './why';
import working_process from './working_process';

export {
	advice_list,
	blockquote,
	content,
	delivery_method,
	faq,
	info,
	payment_information,
	proceed_to_checkout,
	requirements,
	review_and_pay,
	reviews,
	shipping_information,
	step_toolbar,
	values,
	why,
	working_process,
};

export const components = {
	advice_list: advice_list,
	blockquote: blockquote,
	content: content,
	delivery_method: delivery_method,
	faq: faq,
	info: info,
	payment_information: payment_information,
	proceed_to_checkout: proceed_to_checkout,
	requirements: requirements,
	review_and_pay: review_and_pay,
	reviews: reviews,
	shipping_information: shipping_information,
	step_toolbar: step_toolbar,
	values: values,
	why: why,
	working_process: working_process,
};
