// Code generated by Slice Machine. DO NOT EDIT.

import advice_list from './advice_list'
import delivery_method from './delivery_method'
import faq from './faq'
import payment_information from './payment_information'
import proceed_to_checkout from './proceed_to_checkout'
import review_and_pay from './review_and_pay'
import reviews from './reviews'
import shipping_information from './shipping_information'
import step_toolbar from './step_toolbar'
import working_process from './working_process'
import values from './values'
import info from './info'
import why from './why'

export {
  advice_list,
  delivery_method,
  faq,
  payment_information,
  proceed_to_checkout,
  review_and_pay,
  reviews,
  shipping_information,
  step_toolbar,
  working_process,
  values,
  info,
  why,
}

export const components = {
  advice_list,
  delivery_method,
  faq,
  payment_information,
  proceed_to_checkout,
  review_and_pay,
  reviews,
  shipping_information,
  step_toolbar,
  working_process,
  values,
  info,
  why,
}
