fragment Cart on Cart {
  defaultCurrency {
    ...Currency
  }
  billingAddress {
    ...BillingAddress
  }
  shippingAddress {
    ...ShippingAddress
  }
  items {
    ...CartItem
  }
  promoCode
  shippingType
  remarks
  expeditingService
}