export const countries = [
  {
    id: 1,
    country: 'Afghanistan',
    countryCode: 'AF',
    type: 'Passport',
  },
  {
    id: 7,
    country: 'Algeria',
    countryCode: 'DZ',
    type: 'Passport',
  },
  {
    id: 15,
    country: 'Argentina',
    countryCode: 'AR',
    type: 'Passport',
  },
  {
    id: 23,
    country: 'Australia',
    countryCode: 'AU',
    type: 'Passport',
  },
  {
    id: 30,
    country: 'Austria',
    countryCode: 'AT',
    type: 'Passport',
  },
  {
    id: 36,
    country: 'Bahrain',
    countryCode: 'BH',
    type: 'Passport',
  },
  {
    id: 39,
    country: 'Bangladesh',
    countryCode: 'BD',
    type: 'Passport',
  },
  {
    id: 45,
    country: 'Barbados',
    countryCode: 'BB',
    type: 'Passport',
  },
  {
    id: 46,
    country: 'Belarus',
    countryCode: 'BY',
    type: 'Passport',
  },
  {
    id: 51,
    country: 'Belgium',
    countryCode: 'BE',
    type: 'Passport',
  },
  {
    id: 54,
    country: 'Benin',
    countryCode: 'BJ',
    type: 'Passport',
  },
  {
    id: 56,
    country: 'Bhutan',
    countryCode: 'BT',
    type: 'Passport',
  },
  {
    id: 58,
    country: 'Botswana',
    countryCode: 'BW',
    type: 'Passport',
  },
  {
    id: 64,
    country: 'Brazil',
    countryCode: 'BR',
    type: 'Passport',
  },
  {
    id: 68,
    country: 'Brunei',
    countryCode: 'BN',
    type: 'Passport',
  },
  {
    id: 70,
    country: 'Bulgaria',
    countryCode: 'BG',
    type: 'Passport',
  },
  {
    id: 75,
    country: 'Cambodia',
    countryCode: 'KH',
    type: 'Passport',
  },
  {
    id: 85,
    country: 'Canada',
    countryCode: 'CA',
    type: 'Passport',
  },
  {
    id: 89,
    country: 'Chad',
    countryCode: 'TD',
    type: 'Passport',
  },
  {
    id: 93,
    country: 'China',
    countryCode: 'CN',
    type: 'Passport',
  },
  {
    id: 110,
    country: 'Croatia',
    countryCode: 'HR',
    type: 'Passport',
  },
  {
    id: 112,
    country: 'Cyprus',
    countryCode: 'CY',
    type: 'Passport',
  },
  {
    id: 116,
    country: 'Czech Republic',
    countryCode: 'CZ',
    type: 'Passport',
  },
  {
    id: 119,
    country: 'Denmark',
    countryCode: 'DK',
    type: 'Passport',
  },
  {
    id: 124,
    country: 'Djibouti',
    countryCode: 'DJ',
    type: 'Passport',
  },
  {
    id: 126,
    country: 'Dominica',
    countryCode: 'DM',
    type: 'Passport',
  },
  {
    id: 127,
    country: 'Egypt',
    countryCode: 'EG',
    type: 'Passport',
  },
  {
    id: 133,
    country: 'Estonia',
    countryCode: 'EE',
    type: 'Passport',
  },
  {
    id: 141,
    country: 'Ethiopia',
    countryCode: 'ET',
    type: 'Passport',
  },
  {
    id: 146,
    country: 'Fiji',
    countryCode: 'FJ',
    type: 'Passport',
  },
  {
    id: 147,
    country: 'Finland',
    countryCode: 'FI',
    type: 'Passport',
  },
  {
    id: 152,
    country: 'France',
    countryCode: 'FR',
    type: 'Passport',
  },
  {
    id: 160,
    country: 'Georgia',
    countryCode: 'GE',
    type: 'Passport',
  },
  {
    id: 163,
    country: 'Germany',
    countryCode: 'DE',
    type: 'Passport',
  },
  {
    id: 169,
    country: 'Ghana',
    countryCode: 'GH',
    type: 'Passport',
  },
  {
    id: 170,
    country: 'Greece',
    countryCode: 'GR',
    type: 'Passport',
  },
  {
    id: 176,
    country: 'Guyana',
    countryCode: 'GY',
    type: 'Passport',
  },
  {
    id: 179,
    country: 'Hong Kong',
    countryCode: 'HK',
    type: 'Passport',
  },
  {
    id: 181,
    country: 'Hungary',
    countryCode: 'HU',
    type: 'Passport',
  },
  {
    id: 188,
    country: 'India',
    countryCode: 'IN',
    type: 'Passport',
  },
  {
    id: 202,
    country: 'Indonesia',
    countryCode: 'ID',
    type: 'Passport',
  },
  {
    id: 206,
    country: 'Iraq',
    countryCode: 'IQ',
    type: 'Passport',
  },
  {
    id: 211,
    country: 'Ireland',
    countryCode: 'IE',
    type: 'Passport',
  },
  {
    id: 217,
    country: 'Israel',
    countryCode: 'IL',
    type: 'Passport',
  },
  {
    id: 222,
    country: 'Italy',
    countryCode: 'IT',
    type: 'Passport',
  },
  {
    id: 225,
    country: 'Jamaica',
    countryCode: 'JM',
    type: 'Passport',
  },
  {
    id: 229,
    country: 'Japan',
    countryCode: 'JP',
    type: 'Passport',
  },
  {
    id: 240,
    country: 'Jordan',
    countryCode: 'JO',
    type: 'Passport',
  },
  {
    id: 246,
    country: 'Kazakhstan',
    countryCode: 'KZ',
    type: 'Passport',
  },
  {
    id: 252,
    country: 'Kenya',
    countryCode: 'KE',
    type: 'Passport',
  },
  {
    id: 254,
    country: 'Kuwait',
    countryCode: 'KW',
    type: 'Passport',
  },
  {
    id: 260,
    country: 'Kyrgyzstan',
    countryCode: 'KG',
    type: 'Passport',
  },
  {
    id: 263,
    country: 'Laos',
    countryCode: 'LA',
    type: 'Passport',
  },
  {
    id: 266,
    country: 'Lebanon',
    countryCode: 'LB',
    type: 'Passport',
  },
  {
    id: 271,
    country: 'Liberia',
    countryCode: 'LR',
    type: 'Passport',
  },
  {
    id: 273,
    country: 'Libya',
    countryCode: 'LY',
    type: 'Passport',
  },
  {
    id: 276,
    country: 'Lithuania',
    countryCode: 'LT',
    type: 'Passport',
  },
  {
    id: 278,
    country: 'Macau',
    countryCode: 'MO',
    type: 'Passport',
  },
  {
    id: 281,
    country: 'Malawi',
    countryCode: 'MW',
    type: 'Passport',
  },
  {
    id: 284,
    country: 'Malaysia',
    countryCode: 'MY',
    type: 'Passport',
  },
  {
    id: 287,
    country: 'Maldives',
    countryCode: 'MV',
    type: 'Passport',
  },
  {
    id: 288,
    country: 'Malta',
    countryCode: 'MT',
    type: 'Passport',
  },
  {
    id: 291,
    country: 'Mauritius',
    countryCode: 'MU',
    type: 'Passport',
  },
  {
    id: 298,
    country: 'Mongolia',
    countryCode: 'MN',
    type: 'Passport',
  },
  {
    id: 302,
    country: 'Morocco',
    countryCode: 'MA',
    type: 'Passport',
  },
  {
    id: 308,
    country: 'Namibia',
    countryCode: 'NA',
    type: 'Passport',
  },
  {
    id: 313,
    country: 'Nepal',
    countryCode: 'NP',
    type: 'Passport',
  },
  {
    id: 315,
    country: 'Netherlands',
    countryCode: 'NL',
    type: 'Passport',
  },
  {
    id: 333,
    country: 'Norway',
    countryCode: 'NO',
    type: 'Passport',
  },
  {
    id: 335,
    country: 'Oman',
    countryCode: 'OM',
    type: 'Passport',
  },
  {
    id: 343,
    country: 'Pakistan',
    countryCode: 'PK',
    type: 'Passport',
  },
  {
    id: 348,
    country: 'Palestinian Territories',
    countryCode: 'PS',
    type: 'Passport',
  },
  {
    id: 351,
    country: 'Papua New Guinea',
    countryCode: 'PG',
    type: 'Passport',
  },
  {
    id: 356,
    country: 'Philippines',
    countryCode: 'PH',
    type: 'Passport',
  },
  {
    id: 360,
    country: 'Poland',
    countryCode: 'PL',
    type: 'Passport',
  },
  {
    id: 369,
    country: 'Portugal',
    countryCode: 'PT',
    type: 'Passport',
  },
  {
    id: 374,
    country: 'Qatar',
    countryCode: 'QA',
    type: 'Passport',
  },
  {
    id: 380,
    country: 'Russia',
    countryCode: 'RU',
    type: 'Passport',
  },
  {
    id: 394,
    country: 'Saint Kitts and Nevis',
    countryCode: 'KN',
    type: 'Passport',
  },
  {
    id: 396,
    country: 'Samoa',
    countryCode: 'WS',
    type: 'Passport',
  },
  {
    id: 398,
    country: 'Saudi Arabia',
    countryCode: 'SA',
    type: 'Passport',
  },
  {
    id: 403,
    country: 'Seychelles',
    countryCode: 'SC',
    type: 'Passport',
  },
  {
    id: 408,
    country: 'Singapore',
    countryCode: 'SG',
    type: 'Passport',
  },
  {
    id: 416,
    country: 'South Africa',
    countryCode: 'ZA',
    type: 'Passport',
  },
  {
    id: 422,
    country: 'Spain',
    countryCode: 'ES',
    type: 'Passport',
  },
  {
    id: 431,
    country: 'Sri Lanka',
    countryCode: 'LK',
    type: 'Passport',
  },
  {
    id: 435,
    country: 'Sudan',
    countryCode: 'SD',
    type: 'Passport',
  },
  {
    id: 438,
    country: 'Suriname',
    countryCode: 'SR',
    type: 'Passport',
  },
  {
    id: 443,
    country: 'Sweden',
    countryCode: 'SE',
    type: 'Passport',
  },
  {
    id: 446,
    country: 'Switzerland',
    countryCode: 'CH',
    type: 'Passport',
  },
  {
    id: 448,
    country: 'Syria',
    countryCode: 'SY',
    type: 'Passport',
  },
  {
    id: 451,
    country: 'Taiwan',
    countryCode: 'TW',
    type: 'Passport',
  },
  {
    id: 456,
    country: 'Tajikistan',
    countryCode: 'TJ',
    type: 'Passport',
  },
  // {
  //   id: 458,
  //   country: 'Tanzania',
  //   countryCode: null,
  //   type: 'Passport'
  // },
  // {
  //   id: 459,
  //   country: 'Thailand',
  //   countryCode: null,
  //   type: 'Passport'
  // },
  {
    id: 468,
    country: 'Togo',
    countryCode: 'TG',
    type: 'Passport',
  },
  {
    id: 469,
    country: 'Tunisia',
    countryCode: 'TN',
    type: 'Passport',
  },
  {
    id: 475,
    country: 'Turkey',
    countryCode: 'TR',
    type: 'Passport',
  },
  {
    id: 477,
    country: 'Turkmenistan',
    countryCode: 'TM',
    type: 'Passport',
  },
  {
    id: 478,
    country: 'Uganda',
    countryCode: 'UG',
    type: 'Passport',
  },
  {
    id: 486,
    country: 'United Arab Emirates',
    countryCode: 'AE',
    type: 'Passport',
  },
  {
    id: 489,
    country: 'United Kingdom',
    countryCode: 'GB',
    type: 'Passport',
  },
  {
    id: 495,
    country: 'United States',
    countryCode: 'US',
    type: 'Passport',
  },
  {
    id: 506,
    country: 'Yemen',
    countryCode: 'YE',
    type: 'Passport',
  },
  {
    id: 511,
    country: 'Zambia',
    countryCode: 'ZM',
    type: 'Passport',
  },
  {
    id: 513,
    country: 'Zimbabwe',
    countryCode: 'ZW',
    type: 'Passport',
  },
]
